Compare entire vector since last Alignment against MinimumDeltaDistance
mapbox/mapbox-arkit-unity pull request #17
Opened 2017-11-17 15:49 UTC by Crashthatch

Fixes #16.

I'm not entirely sure what this line is doing:

    var originOffset = _arNodes[_count - 2] - headingQuaternion * _gpsPositions[_count - 2];

It looks like it's finding the distance between the last recorded AR position and the last recorded GPS position (after rotating GPS position into AR space using the *new* headingQuaternion ). So originOffset would be the error in the *previous* alignment? I don't understand why this is useful?

I did test in the real world. It wasn't very accurate, but I think this was a pre-existing issue - it's hard to tell.

2017-11-17 17:15 UTC, david-rhodes commented
> It looks like it's finding the distance between the last recorded AR position and the last recorded GPS position (after rotating GPS position into AR space using the new headingQuaternion ). So originOffset would be the error in the previous alignment? I don't understand why this is useful?

The origin offset is supposed to represent the delta between the map (root) origin and the location coordinates (from GPS) inside the map. But, we can't simply keep the original origin offset because it could have been wrong (initial GPS updates are often very poor/wrong). Therefore, we constantly update our origin using previous node data. In effect, this makes it so that error is always relative to the previous nodes.

I tested your changes and I'm afraid to say that something is amiss. If you check the log below, you will notice that the heading values reported are "ping-ponging." This suggests that some cached vectors are being used improperly or being overwritten incorrectly. You can see that `offset` (position for alignment) is also bouncing back and forth.
![img_2750](https://user-images.githubusercontent.com/23202691/32959517-0ffdf55a-cb7f-11e7-99ac-2abce5aa8e07.PNG)

2017-11-17 17:16 UTC, david-rhodes requested changes
Please find source of incorrect heading values with every other update.

2017-11-17 19:50 UTC, Crashthatch commented
Ok I think that's stopped it bouncing around - I'm now storing the previousPosition rather than the previous vector. Again, I tested, but it's difficult to compare to the previous performance.

2017-11-17 22:38 UTC, david-rhodes commented
I think it will be hard to validate on device, given you fixed a bug that would only occasionally occur and we cannot easily force that bug.

That said, it definitely still works. I did notice, however, that the farther I walk, the more the position inside the alignment starts to ping pong back and forth. I reverted my changes and tested again with the same results, so this one is not on you. 

Something weird is happening to the `originOffset` or `delta`, is my guess. I'll investigate, but this is approved for now.

2017-11-17 22:39 UTC, david-rhodes approved these changes

2017-11-20 22:37 UTC, david-rhodes commented
@Crashthatch I found the source of the "ping ponging" position offset bug! It's actually in the `AverageHeadingAlignmentStrategy`. I assume it has to do with me "undoing" the rotation before reapplying. Thought you might want to know, in case this causes issues for you. In the meantime, you can use another alignment strategy (snap?).

2017-11-20 22:37 UTC, merged

2017-11-21 16:41 UTC, Crashthatch commented
@david-rhodes Thanks, I'll use the snapAlignmentStrategy for now.