ARTabletop setup
mapbox/mapbox-arkit-unity pull request #32
Opened 2017-12-22 21:58 UTC by lauri-rustanius

Added ARTabletop setup folder which contains all the logic, materials, scripts, shader and a prefab to run the ARTabletop demo. Also added ARTabletopScene to MapboxARScenes folder.

@atripathi-mb can you look at these and do a review before merging?

2018-01-03 23:24 UTC, abhishektrip requested changes
Logic looks good 👍

2018-01-03 23:24 UTC, abhishektrip commented on Assets/ARTabletop/Scripts/PlaceMapOnARPlane.cs
> +	void Start ()
Fix formatting.

2018-01-03 23:24 UTC, abhishektrip commented on Assets/ARTabletop/Shader/Clip_Box.shader
> +      //_Origin ("Origin (World Space)", Vector) = (0,0,0,0)
Remove unused code.

2018-01-03 23:24 UTC, abhishektrip commented on Assets/ARTabletop/Shader/Clip_Box.shader
> +      struct Input {
Fix formatting. Use brackets in new line.

2018-01-03 23:24 UTC, abhishektrip commented on Assets/ARTabletop/Shader/Clip_Box.shader
> +      half _Glossiness;
fix indentation

2018-01-03 23:24 UTC, abhishektrip commented on Assets/ARTabletop/Shader/Clip_Box.shader
> +      void surf (Input IN, inout SurfaceOutputStandard o) {
Bracket in next line.

2018-01-03 23:24 UTC, abhishektrip commented on Assets/ARTabletop/Shader/Clip_Box.shader
> +		  // Vector3 newDir = Mathf.Cos(angle) * dir + Mathf.Sin(angle) * Vector3.Cross(axis, dir) + (1.0f - Mathf.Cos(angle)) * Vector3.Dot(axis,dir) * axis;
remove unused code.

2018-01-03 23:24 UTC, abhishektrip commented on Assets/ARTabletop/Shader/Clip_Box.shader
> +	  	  //dir = normalize(dir);
remove unused code.

2018-01-03 23:24 UTC, abhishektrip commented on Assets/ARTabletop/Shader/Clip_Box.shader
> + 		  // replaced
remove unused code.

2018-01-03 23:24 UTC, abhishektrip commented on Assets/ARTabletop/Shader/Clip_Box.shader
> +      	  // all need to be less than size
Fix indentation

2018-01-03 23:24 UTC, abhishektrip commented on Assets/ARTabletop/Shader/Clip_Box.shader
> +      	  //clip(t);
remove unused code.

2018-01-03 23:24 UTC, abhishektrip commented on Assets/ARTabletop/Shader/Clip_Box.shader
> +          // min = 0 // value = dist // max = _ConvertDistance
remove unused code.

2018-01-03 23:24 UTC, abhishektrip commented on Assets/ARTabletop/Scripts/PlaceMapOnARPlane.cs
> +public class PlaceMapOnARPlane : MonoBehaviour {
Brackets in the next line please.

2018-01-03 23:24 UTC, abhishektrip commented on Assets/ARTabletop/Scripts/ARTableTileProvider.cs
> +            _currentTile = TileCover.CoordinateToTileId(_basicMap.WorldToGeoPosition(_targetTransform.position),(int)_map.Zoom);
indentation.

2018-01-03 23:24 UTC, abhishektrip commented on Assets/ARTabletop/Scripts/ARTableTileProvider.cs
> +                _initialized = true;
indentation

2018-01-03 23:24 UTC, abhishektrip commented on Assets/ARTabletop/Scripts/ARTableTileProvider.cs
> +        private AbstractMap _basicMap;
indentation

2018-01-03 23:24 UTC, abhishektrip commented on Assets/ARTabletop/Scripts/ARTableTileProvider.cs
> +    using System.Collections.Generic;
indentation

2018-01-18 17:37 UTC, wilhelmberg requested changes
@lauri-rustanius still some formatting issues.

2018-01-18 17:37 UTC, BergWerkGIS commented on Assets/ARTabletop/Scripts/ARPlaneHandler.cs
> +﻿using UnityEngine;
Whole file has spaces, please use tabs.

2018-01-18 17:37 UTC, BergWerkGIS commented on Assets/ARTabletop/Scripts/ARTableTileProvider.cs
> +﻿using System.Linq;
Whole file has mixed tabs and spaces.

2018-01-18 17:37 UTC, BergWerkGIS commented on Assets/ARTabletop/Scripts/PlaceMapOnARPlane.cs
> +﻿using UnityEngine;
Whole file has spaces.

2018-01-18 17:37 UTC, BergWerkGIS commented on Assets/ARTabletop/Scripts/UpdateShaderCoordinatesByARPlane.cs
> +﻿using System.Collections;
Whole file has spaces.

2018-01-18 17:37 UTC, BergWerkGIS commented on Assets/ARTabletop/Shader/Clip_Box.shader
> +﻿
Whole file has mixed tabs and spaces.

2018-01-19 10:19 UTC, wilhelmberg approved these changes

2018-01-19 10:20 UTC, BergWerkGIS commented
@lauri-rustanius 
I took the liberty of fixing the remaining formatting issues so that your are free to merge from my point of view.

2018-02-06 02:46 UTC, merged